---
AWSTemplateFormatVersion: 2010-09-09
Description: >
  CloudFormation template to create a secure,
  compliant S3 data lake bucket with optional versioning,
  lifecycle policies, and encryption settings.
Metadata:
  Repository: >-
    https://-.com/projects/repos/deployer-patterns/browse

Parameters:
  BucketName:
    Type: String
    Description: >
      Optional? Specify bucket name, or leave blank for auto-generation.
    Default: ""

  S3ObjectVersioning:
    Type: String
    Description: Enable or suspend versioning.
    AllowedValues:
      - Enabled
      - Suspended
    Default: Enabled

  LifecyclePolicy:
    Type: String
    Description: >
      Apply lifecycle rules for intelligent tiering and archival.
    AllowedValues:
      - Enabled
      - Disabled
    Default: Enabled

  VersionedObjectExpiration:
    Type: Number
    Description: >
      Number of days before old versioned objects expire.
    Default: 65

  CustomKmsKey:
    Type: String
    Description: >
      ARN for a custom KMS CMK for encryption.
    Default: ""

  GBTSKeychain:
    Type: String
    Description: Use GBTS keychain for encryption.
    AllowedValues:
      - Enabled
      - Disabled
    Default: Disabled

Conditions:
  NameBucket: !Not [!Equals [!Ref BucketName, ""]]
  ProvideCK: !Not [!Equals [!Ref CustomKmsKey, ""]]
  UseGBTSKeychain: !Equals [!Ref GBTSKeychain, "Enabled"]
  VersionedLifecycle: !And
    - !Equals [!Ref S3ObjectVersioning, "Enabled"]
    - !Equals [!Ref LifecyclePolicy, "Enabled"]
  NonVersionedLifecycle: !And
    - !Equals [!Ref S3ObjectVersioning, "Suspended"]
    - !Equals [!Ref LifecyclePolicy, "Enabled"]

Resources:
  # -------------------------------
  # Main S3 Data Lake Bucket
  # -------------------------------
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !If
        - NameBucket
        - !Ref BucketName
        - !Ref "AWS::NoValue"
      OwnershipControls:
        Rules:
          - ObjectOwnership: BucketOwnerEnforced
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      VersioningConfiguration:
        Status: !Ref S3ObjectVersioning
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: aws:kms
              KMSMasterKeyID: !If
                - ProvideCK
                - !Ref CustomKmsKey
                - !If
                  - UseGBTSKeychain
                  - !ImportValue gbtskeychain
                  - !Ref "AWS::NoValue"
      LifecycleConfiguration:
        Rules: !If
          - VersionedLifecycle
          -
            - Id: VersionedObjectRule
              Status: Enabled
              ExpirationInDays: !Ref VersionedObjectExpiration
              NoncurrentVersionTransitions:
                - TransitionInDays: 30
                  StorageClass: STANDARD_IA
                - TransitionInDays: 60
                  StorageClass: GLACIER
              AbortIncompleteMultipartUpload:
                DaysAfterInitiation: 7
          - !If
            - NonVersionedLifecycle
            -
              - Id: StandardObjectRule
                Status: Enabled
                Transitions:
                  - TransitionInDays: 30
                    StorageClass: STANDARD_IA
                  - TransitionInDays: 60
                    StorageClass: GLACIER
                AbortIncompleteMultipartUpload:
                  DaysAfterInitiation: 7
            - !Ref "AWS::NoValue"

  # -------------------------------
  # Enforce HTTPS / TLS-only Access
  # -------------------------------
  S3BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref S3Bucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: EnforceTLS
            Effect: Deny
            Principal:
              AWS: !Sub "arn:aws:iam::${AWS::AccountId}:root"
            Action: s3:*
            Resource:
              - !GetAtt S3Bucket.Arn
              - !Sub "${S3Bucket.Arn}/*"
            Condition:
              Bool:
                aws:SecureTransport: false

Outputs:
  # -------------------------------
  # Exported Outputs (for other stacks)
  # -------------------------------
  S3BucketName:
    Description: Name of the created S3 bucket
    Value: !Ref S3Bucket
    Export:
      Name: !Sub "${AWS::StackName}-S3BucketName"

  S3BucketArn:
    Description: ARN of the created S3 bucket
    Value: !GetAtt S3Bucket.Arn
    Export:
      Name: !Sub "${AWS::StackName}-S3BucketArn"

  StackName:
    Description: CloudFormation stack name
    Value: !Ref AWS::StackName
