AWSTemplateFormatVersion: '2010-09-09'
Description: Simple S3 bucket example

Parameters:
  EnvironmentName:
    Type: String
    Description: The name of the environment (dev, stg, prod)
  BucketName:
    Type: String
    Description: The name of the S3 bucket

Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketName
      Tags:
        - Key: Environment
          Value: !Ref EnvironmentName

Outputs:
  BucketName:
    Description: The created bucket name
    Value: !Ref S3Bucket
