---
AWSTemplateFormatVersion: '2010-09-09'
Description: >
  End-to-End Data Lake Glue Stack
  - Imports S3 Data Lake bucket automatically (based on environment)
  - Creates Glue Database and Crawler to auto-detect schema

Parameters:
  EnvironmentName:
    Type: String
    Description: Environment name (e.g. dev, stg, prod)

Resources:
  # -------------------------------
  # IAM Role for Glue
  # -------------------------------
  GlueServiceRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "glue-service-role-${EnvironmentName}"
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: glue.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSGlueServiceRole
      Policies:
        - PolicyName: S3AccessPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                  - s3:ListBucket
                Resource:
                  - !Sub
                    - '${S3BucketArn}'
                    - S3BucketArn:
                        Fn::ImportValue: !Sub
                          's3-${EnvironmentName}-S3BucketArn'
                  - !Sub
                    - '${S3BucketArn}/*'
                    - S3BucketArn:
                        Fn::ImportValue: !Sub
                          's3-${EnvironmentName}-S3BucketArn'

  # -------------------------------
  # Glue Database
  # -------------------------------
  GlueDatabase:
    Type: AWS::Glue::Database
    Properties:
      CatalogId: !Ref "AWS::AccountId"
      DatabaseInput:
        Name: !Sub "datalake_${EnvironmentName}"
        Description: !Sub "Glue database for ${EnvironmentName} environment"

  # -------------------------------
  # Glue Crawler
  # -------------------------------
  GlueCrawler:
    Type: AWS::Glue::Crawler
    Properties:
      Name: !Sub "crawler-${EnvironmentName}"
      Role: !GetAtt GlueServiceRole.Arn
      DatabaseName: !Ref GlueDatabase
      Targets:
        S3Targets:
          - Path: !Sub
              - 's3://${S3BucketName}/'
              - S3BucketName:
                  Fn::ImportValue: !Sub
                    's3-${EnvironmentName}-S3BucketName'
      SchemaChangePolicy:
        UpdateBehavior: UPDATE_IN_DATABASE
        DeleteBehavior: LOG

Outputs:
  GlueDatabaseName:
    Description: Glue Database name
    Value: !Ref GlueDatabase

  GlueCrawlerName:
    Description: Glue Crawler name
    Value: !Ref GlueCrawler
