name: Deploy S3 CloudFormation

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Target environment (dev, stg, prod)"
        required: true
        default: "dev"
        type: choice
        options:
          - dev
          - stg
          - prod

jobs:
  deploy:
    name: Deploy to ${{ github.event.inputs.environment }}
    runs-on: ubuntu-latest

    env:
      CFN_TEMPLATE: infra/template.yaml
      AWS_REGION: us-east-1

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set environment AWS credentials
        run: |
          ENV=${{ github.event.inputs.environment }}
          echo "ENVIRONMENT=$ENV" >> $GITHUB_ENV

          if [ "$ENV" == "dev" ]; then
            echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID_DEV }}" >> $GITHUB_ENV
            echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY_DEV }}" >> $GITHUB_ENV
            echo "STACK_NAME=s3-bucket-dev" >> $GITHUB_ENV
          elif [ "$ENV" == "stg" ]; then
            echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID_STG }}" >> $GITHUB_ENV
            echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY_STG }}" >> $GITHUB_ENV
            echo "STACK_NAME=s3-bucket-stg" >> $GITHUB_ENV
          elif [ "$ENV" == "prod" ]; then
            echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID_PROD }}" >> $GITHUB_ENV
            echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY_PROD }}" >> $GITHUB_ENV
            echo "STACK_NAME=s3-bucket-prod" >> $GITHUB_ENV
          fi

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Deploy CloudFormation stack
        run: |
          aws cloudformation deploy \
            --template-file $CFN_TEMPLATE \
            --stack-name $STACK_NAME \
            --capabilities CAPABILITY_NAMED_IAM \
            --parameter-overrides file://parameters-${{ env.ENVIRONMENT }}.json \
            --no-fail-on-empty-changeset
