name: Deploy Athena Stack

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Target environment"
        required: true
        default: "dev"
        type: choice
        options:
          - dev
          - stg
          - prod
      action:
        description: "Deploy or destroy"
        required: true
        default: "deploy"
        type: choice
        options:
          - deploy
          - destroy
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      action:
        required: true
        type: string

jobs:
  athena:
    runs-on: aws

    steps:
      - uses: actions/checkout@v4

      - name: Set env vars
        run: |
          echo "ENV=${{ inputs.environment }}" >> $GITHUB_ENV
          echo "STACK_NAME=athena-${{ inputs.environment }}" >> $GITHUB_ENV
          echo "TEMPLATE_PATH=infra/athena/Athena.yaml" >> $GITHUB_ENV
          echo "PARAM_FILE=parameters/athena-${{ inputs.environment }}.json" >> $GITHUB_ENV

      - name: Verify IAM Role
        run: aws sts get-caller-identity

      - name: Deploy or Destroy
        run: |
          if [ "${{ inputs.action }}" == "deploy" ]; then
            aws cloudformation deploy \
              --stack-name "$STACK_NAME" \
              --template-file "$TEMPLATE_PATH" \
              --capabilities CAPABILITY_NAMED_IAM \
              --parameter-overrides file://"$PARAM_FILE" \
              --no-fail-on-empty-changeset
          else
            aws cloudformation delete-stack --stack-name "$STACK_NAME"
            aws cloudformation wait stack-delete-complete --stack-name "$STACK_NAME"
          fi
